### ISSUE TITLE
UI need some improvement

### ISSUE THREAD

**Issue by niteshjitender** [origranot/url-shortner#12]
I have made these changes.
![URL shortner clean UI ](https://user-images.githubusercontent.com/43808239/194126093-15d8ea73-29bc-40eb-b1b8-adc61cec12d2.png)

Please check this [PR](https://github.com/origranot/url-shortner/pull/11)

**Comment by origranot** [comment]
Hey @niteshjitender 

Thank you for the pr.
The last PR already changed the UI.

What do you think about adding a cool animation?
